### ISSUE TITLE
Deploy with Github actions and Github pages.

### ISSUE THREAD

**Issue by viticis** [lyricat/mornin.fm#33]
When I realized this was a front-end-only project, I thought github actions and github pages were a better approach than docker.
So I wrote an [action yml](https://github.com/viticis/mornin/blob/master/.github/workflows/master.yml) and deployed it on [fm.viticis.com](https://fm.viticis.com).
And it looks ok.
But when I join the room using a link like [fm.viticis.com/test](https://fm.viticis.com/test), github returns a 404.
When I open the home page and type "test" everything works fine.
Will you help me with this problem?
Thanks.

**Comment by lyricat** [comment]
By default the project use “history” router mode, which needs some configurations to the http server to make sure the requested path be redirected to the index.html.

**Comment by lyricat** [comment]
You may want to check it https://router.vuejs.org/guide/essentials/history-mode.html#example-server-configurations

**Comment by viticis** [comment]
Thx, I have solved this problem.
Do you think this feature can be merged into your project?
If you agree, I'll push a merge request after I clean up the code.

**Comment by lyricat** [comment]
sure. but it should be an option that would not affect other forks

**Comment by viticis** [comment]
Actually, the github action will only be executed `yarn generate` and pushed to the gh-pages branch, you still need to go to the repository Settings -> Pages and select gh-pages to deploy.
So it will not affect other forks.
What do you think?

**Comment by lyricat** [comment]
I think it's fine.
